# Generated by Django 3.1.4 on 2021-01-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_main_page', '0005_task_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
    ]
