# Generated by Django 3.1.4 on 2021-01-24 21:33

from django.db import migrations
import crm_main_page.mydbfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm_main_page', '0006_auto_20210124_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=crm_main_page.mydbfields.EuDateField(),
        ),
    ]
