# Generated by Django 3.1.4 on 2020-12-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0004_auto_20201224_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_budget',
            field=models.IntegerField(default=0),
        ),
    ]
